hw4
S-Pavel-Alex/Homework-epam pull request #7
Opened 2021-11-25 23:17 UTC by S-Pavel-Alex

2021-12-02 14:23 UTC, megagnom37 requested changes
Проверил - исправляй

2021-12-02 14:23 UTC, megagnom37 commented on homework4/task1.py
> +        return False
Ты должен зарейзить эксепшен а не вернуть False.
Внимательнее читай задание

2021-12-02 14:23 UTC, megagnom37 commented on homework4/task2.py
> +            total += 1
У строки есть замечательный метод **count**

2021-12-02 14:23 UTC, megagnom37 commented on homework4/task2.py
> +    return response.read().decode('utf-8')
А если тут возникнет эксепшен?
Вниметльнее читай задание - тебе нужно зарейзить в этом случае другой эксепшен

2021-12-02 14:23 UTC, megagnom37 commented on homework4/task4.py
> +    fiz_buz_list = []
Зачем создавать еще один лист если можно модифицировать старый?
х2 памяти жрешь да еще и замедляешь программу из-за дополнительной алокации памяти для листа второго

2021-12-02 14:23 UTC, megagnom37 commented on homework4/task4.py
> +    doctest.testmod()
Это зачем?

2021-12-02 14:23 UTC, megagnom37 commented on tests/homework4/test_task1.py
> +
"Круто"
Чиатй внимательнее задание - тебе не нужно руками создавать файлы а делать это нужно динамически + динамически удалять файлы после теста

2021-12-02 14:23 UTC, megagnom37 commented on tests/homework4/test_task1_with_param.py
> +
А это тестирование вообще зачем?

2021-12-02 14:23 UTC, megagnom37 commented on homework4/task2.py
> +def count_dots_on_i(url: str) -> int:
Где тесты к этой функции?

2021-12-02 14:23 UTC, megagnom37 commented on tests/homework4/test_task3.py
> +    assert my_precious_logger('error') is sys.stderr.write('error')
Какая "то страшная чушь" =) 
Почитай про фикстуру capsys в pytest

2021-12-08 09:20 UTC, megagnom37 requested changes
Проверил - исправляй

2021-12-08 09:20 UTC, megagnom37 commented on homework4/task1.py
> +            for line in text:
Зачем здесь цикл если ты сразу return делаешь? 
Тебе только первую строчку надо считать

2021-12-08 09:20 UTC, megagnom37 commented on homework4/task2.py
> +    text = connect_url_mock(url).text
Полнейший бред. Какие еще моки в исходном коде?

2021-12-08 09:20 UTC, megagnom37 commented on homework4/task4.py
> +            item_index = basic_list.index(item)
Очень плохая идея.
Подумай как без этого сделать - потому что это ужасно не производительно
Заодно посчитай мне О(n) для твоего текущего решения и после того как переделаешь на правильное тоже посчитай и в комментах ответь

2021-12-08 09:20 UTC, megagnom37 commented on tests/conftest.py
> +
Не хватает юзкейсов - например когда в файле нет ничего или когда в первой строке не число а текст и например когда файле больше чем одна строка. Тестируй лучше!

2021-12-08 09:20 UTC, megagnom37 commented on tests/homework4/test_task1.py
> +def test_positive_inside_range(open_correct_file_with_correct_item):
В целом это намного лучше чем было до этого - я зачту это, так как это корректно.
Но в идеале ты мог сделать всего одну фикстуру которая принимала бы на вход текст и записывала его в файл. А различный текст в нее передовал бы через декоратор parametrize

2021-12-08 09:20 UTC, megagnom37 commented on tests/homework4/test_task2.py
> +def test_count_dots_on_i_positive():
не имеет смысла так как исходный код абсолютно неверен

2021-12-08 09:20 UTC, megagnom37 commented on homework4/task3.py
> +        print(text)
Зачем ты заменил sys.stderr.write и sys.stdout.write на print?

2021-12-08 13:50 UTC, S-Pavel-Alex commented on homework4/task4.py
> +            item_index = basic_list.index(item)
O(5n) - это прошлое решение
O(3n) - это новое решение.
Попробую описать как я понял, чтоб разобраться поправишь меня.
В прошлом случае для одного элемента я делал операций: 1. взял элемент, 2. проверил делением, 3. определил индекс, 4. занес в переменную, 5. заменил элемент. т.е. всего 5 операций и в худшем случае их нужно применить ко все n элементам.
В новом случае для одного элемента Я делал: 1. взять элемент, 2. проверить на деление, 3. заменить элемент.
Так?

2021-12-10 08:42 UTC, megagnom37 requested changes
Проверил

2021-12-10 08:42 UTC, megagnom37 commented on homework4/task2.py
> +    return mock_object.text
Так и не исправил

2021-12-10 08:42 UTC, megagnom37 commented on homework4/task3.py
> +        return sys.stdout.write(text)
Зачем тут return

2021-12-10 08:42 UTC, megagnom37 commented on homework4/task4.py
> +    for item in range(len(basic_list)):
A нельзя просто итерироваться по range(n)?
И тогда потом не конвертить str к int?

2021-12-10 09:03 UTC, S-Pavel-Alex commented on homework4/task3.py
> +        return sys.stdout.write(text)
Согласен, не нужно. По привычке написал

2021-12-10 09:03 UTC, S-Pavel-Alex commented on homework4/task4.py
> +    for item in range(len(basic_list)):
Согласен. Так проще

2021-12-14 15:38 UTC, megagnom37 commented on tests/homework4/test_task2.py
> +    assert count_dots_on_i('https://example.com/') == 59
А тут ты в реальный интернет лезешь?

2021-12-14 15:40 UTC, megagnom37 requested changes
Проверил.
Глобальный вопрос - что за мусор у тебя в пулл реквест попадает:
- .idea
- .task2.py.swp

2021-12-14 15:40 UTC, megagnom37 commented on tests/homework4/test_task2.py
> +    assert count_dots_on_i('https://example.com/') == 59
А тут ты в реальный интернет лезешь?

2021-12-16 17:24 UTC, megagnom37 approved these changes
Принято

2021-12-16 17:24 UTC, megagnom37 commented on tests/homework4/test_task2.py
> +        assert count_dots_on_i('https://example.com/') == 5
Можно было просто параметризовать text и eexpected_result через декоратор pytest

2021-12-16 17:27 UTC, S-Pavel-Alex commented on tests/homework4/test_task2.py
> +        assert count_dots_on_i('https://example.com/') == 5
Согласен, но в целом же достаточно одного теста, зачем больше

2021-12-27 15:14 UTC, merged